### ISSUE TITLE
Missing requirements for testing

### ISSUE THREAD

**Issue by gerbyzation** [okfn/docker-ckan#3]
I've been trying to run tests on an extension and found there are some things missing to be able to run tests.

1. install ckan's `dev-requirements.txt` 
This could be done (conditionally) in the Dockerfile, but that would mean there would be a different image build for dev and prod.  Alternatively this could take place in `start_ckan_development.sh` but then every time a new instance is recreated we need to download dependencies.
2. update `test-core.ini` with database, redis and solr settings.
Update in `start_ckan_development.sh` with the paster config-tool? Also does solr need a second core for testing?
3. CKAN is not located in a sibling directory relative to the manually installed extensions, the `use` setting needs to be updated in `test.ini`. 
4. install dev/testing dependencies for specific plugin. 
In `start_ckan_development.sh` it's checking for requirements files, we can add a check for `dev-requirements.txt` to pick dev dependencies up as wel.

Will look at putting a PR together for 2-4 unless you have other suggestions on how to tackle these.

**Comment by amercader** [comment]
> 1. install ckan's `dev-requirements.txt` 

I really don't want to end up with images and scripts that try to work on both production and development environments. Otherwise we end up with the compose setup that we currently have in CKAN core (see eg https://github.com/ckan/ckan/pull/3951). I've tried to cleanly separate both in #5. Would love your thoughts on that.

> 2. update `test-core.ini` with database, redis and solr settings.
Update in `start_ckan_development.sh` with the paster config-tool? Also does solr need a second core for testing?
We need a test database (I think is not a big deal to create it as part of the `db` image build). I think for Redis and Solr is safe to leave as they are. There's no need for a Solr core as the tests use a different site id, so they are not mixed with the default ones.

> 3. CKAN is not located in a sibling directory relative to the manually installed extensions, the `use` setting needs to be updated in `test.ini`. 
Sounds good

> 4. install dev/testing dependencies for specific plugin. 
In `start_ckan_development.sh` it's checking for requirements files, we can add a check for `dev-requirements.txt` to pick dev dependencies up as wel.
Sounds good!

**Comment by gerbyzation** [comment]
I agree with you on 1), will have a look at your PR

**Comment by gerbyzation** [comment]
closed by #4 and #5
