### ISSUE TITLE
/var/lib/ckan/storage/ and /var/lib/ckan/resources/ are owned by root

### ISSUE THREAD

**Issue by chris48s** [okfn/docker-ckan#45]
These should be owned by the `ckan` user out-of-the-box

**Comment by adborden** [comment]
I'm running into this too. It looks like that because some of the CKAN initialization commands are run as root within the Dockerfile and start script, when CKAN creates non-existent directories, they are owned by root.

The tricky thing is that some paster commands should be run as _root_, while some should be run as _ckan_.

https://github.com/okfn/docker-ckan/pull/42 is a catch all and seems like a reasonable fix.

**Comment by amercader** [comment]
I believe this is now fixed (by #46)
